StockControl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('compra/', include("compra.urls")),
]

compra/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name= "index"),
    path('proveedores/nuevo',views.nuevo_proveedor,name="nuevo_proveedor"),
    path('proveedores/listado', views.listado_proveedores, name="listado_proveedores"),
    path('productos/nuevo',views.nuevo_producto,name="nuevo_producto"),   
    path('productos/lista_productos/', views.lista_productos, name='lista_productos'),
    path('list_productos/', views.list_productos, name='list_productos'),
]

compra/models.py
from django.db import models

class Proveedor(models.Model):
    nombre = models.CharField(verbose_name="Nombre",max_length=50)
    apellido = models.CharField(verbose_name="Apellido",max_length=50)
    dni = models.IntegerField(verbose_name="dni")
    
    def __str__(self):
        return self.nombre
    

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.FloatField(default=0)
    stock_actual = models.IntegerField(verbose_name="stock actual")
    proveedor = models.ForeignKey(Proveedor,on_delete=models.CASCADE,related_name="producto")
    

compra/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from .models import *
from django.shortcuts import get_object_or_404,redirect
from django.http.response import JsonResponse

def index(request):

    return HTTPResponse("Hola mundo")

def nuevo_proveedor(request):

    if request.POST:

        Proveedor.objects.create(
            nombre = request.POST["nombre"],
            apellido = request.POST["apellido"],
            dni = request.POST["dni"],
        )
    return render(request,'compra/nuevo_proveedor.html')

def nuevo_producto(request):
    
    proveedores = Proveedor.objects.all()
    
    context = {
        "proveedores": proveedores
    }
    
    if request.POST:
        nombre = request.POST['nombre']    
        precio = request.POST['precio'] 
        stock_actual = request.POST['stock_actual'] 
        proveedor_id = request.POST['proveedor']
        
        Producto.objects.create(
            nombre = nombre,
            precio = precio,
            stock_actual = stock_actual,
            proveedor_id = proveedor_id
        )
        
    return render(request, "compra/nuevo_producto.html", context)

def listado_proveedores(request):
    proveedores = Proveedor.objects.all()
    print(proveedores)
    context = {
        "proveedores": proveedores
    }
    return render(request, "compra/listado_proveedores.html", context)

def list_productos(_request):
    productos = list(Producto.objects.values())
    data = {'productos': productos}
    return JsonResponse(data)

def lista_productos(request):
    return render(request, 'compra/lista_productos.html')

compra/templates/compra/lista_productos.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>lista_productos</title>
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
        <!-- DataTable.js -->
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" />
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" />
                
    </head>
    <body>
        <div class="body">
            <div class="container mt-4" id="tabla">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                        <a href="{% url 'nuevo_producto' %}" id="nuevo"><button class='btn btn-sm btn-primary'>Agregar nuevo Producto</button></a>
                        <div class="table-responsive">
                            <table id="lista_productos" class="table">                                
                                <thead>
                                    <tr>
                                        <th class="centrado">ID</th>
                                        <th class="centrado">NOMBRE</th>
                                        <th class="centrado">PRECIO</th>
                                        <th class="centrado">STOCK ACTUAL</th>
                                        <th class="centrado">PROVEEDOR</th>                                    
                                        <th class="centrado">OPCIONES</th>
                                    </tr>
                                </thead>
                                <tbody id="tabla_cuerpo"></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
        <!-- jQuery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <!-- DataTable.js -->
        <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
        <!-- Custom JS -->
        <script src="{% static 'js/lista_productos.js' %}"></script>
    </body>
</html>

compra/templates/compra/listado_productos.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de productos</title>
</head>
<body>
    <a href="{% url 'nuevo_producto' %}">Agregar nuevo Producto</a>
    <table border="1">
        
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Stock Actual</th>
                <th>Proveedor</th>
            </tr>
        
        
            {% for producto in productos %}
            <tr>
                <td>{{producto.id}}</td>
                <td>{{producto.nombre}}</td>
                <td>{{producto.precio}}</td>
                <td>{{producto.stock_actual}}</td>
                <td>{{producto.proveedor}}</td>

            </tr>
            {% endfor %}
        
    </table>
</body>
</html>

compra/templates/compra/listado_proveedores.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listado de Proveedores</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
</head>
<body>
    <div class="body">
        <div class="container mt-4" id="tabla">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <a href="{% url 'nuevo_proveedor' %}" id="nuevo"><button class='btn btn-sm btn-primary'>Agregar nuevo Proveedor</button></a>
                    <div class="table-responsive">
                        <table id="lista_proveedores" class="table">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>Apellido</th>
                                    <th>DNI</th>
                                </tr>
                            </thead>
                            <tbody id="tabla_cuerpo">
                                {% for proveedor in proveedores %}
                                <tr>
                                    <td>{{proveedor.id}}</td>
                                    <td>{{proveedor.nombre}}</td>
                                    <td>{{proveedor.apellido}}</td>
                                    <td>{{proveedor.dni}}</td>
                                </tr>
                                {% endfor %}
        
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
     <!-- Bootstrap -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

compra/templates/compra/nuevo_producto.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar un nuevo Producto</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
</head>
<body>
    <div class="fondo min-vh-100 d-flex flex-column justify-content-center align-items-center">    
        <div class="contenedo-enlance-formulario w-25">       
            <div class="contenedor-formulario p-5 rounded-bottom shadow p-3 mb-5">
                <h2 class="mb-4 text-center">Registrar Producto</h2>
                <form method="post">
                    {% csrf_token %}
                        <label for="id_nombre">Nombre :</label>
                        <input type="text" name="nombre" id="id_nombre" required>
                        <br>
                        <label for="id_precio">Precio :</label>
                        <input type="floatformat" name="precio" id="id_precio" required>
                        <br>
                        <label for="id_stock_actual">Unidades</label>
                        <input type="number" name="stock_actual" id="id_stock_actual">
                        <br>
                        <label for="proveedor">Proveedor</label>
                        <select name= "proveedor">
                        {% for proveedor in proveedores %}
                            <option value="{{ proveedor.id }}"> {{proveedor.nombre}} </option>
                        {% endfor %}
                        </select>
                        <br><br>
                        <button class='btn btn-sm btn-success'>guardar</button>
                </form>
                <div>
                    <a href="{% url 'lista_productos' %}"><button class='btn btn-sm btn-primary'>Volver a listado de Productos</button></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

compra/templates/compra/nuevo_proveedor.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar un nuevo Proveedor</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
</head>
<body>
    <div class="fondo min-vh-100 d-flex flex-column justify-content-center align-items-center">    
        <div class="contenedo-enlance-formulario w-25">       
            <div class="contenedor-formulario p-5 rounded-bottom shadow p-3 mb-5">
                <h2 class="mb-4 text-center">Registrar Proveedor</h2>
                <form method="post">
                    {% csrf_token %}
                    <label for="id_nombre">Nombre :</label>
                    <input type="text" name="nombre" id="id_nombre" required>
                    <br>
                    <label for="id_apellido">Apellido :</label>
                    <input type="text" name="apellido" id="id_apellido" required>
                    <br>
                    <label for="id_dni">Numero de dni</label>
                    <input type="number" name="dni" id="id_dni" required>
                    <br>                    
                    <button class='btn btn-sm btn-success'>guardar</button>
                </form>
                <div>
                    <a href="{% url 'listado_proveedores' %}"><button class='btn btn-sm btn-primary'>Volver a listado de Proveedores</button></a>
                </div>
            </div>
        </div>
    </div>
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>



<form method="post">
    {% csrf_token %}
    <label for="id_nombre">Nombre :</label>
    <input type="text" name="nombre" id="id_nombre" required>
    <br>
    <label for="id_apellido">Apellido :</label>
    <input type="text" name="apellido" id="id_apellido" required>
    <br>
    <label for="id_dni">Numero de dni</label>
    <input type="number" name="dni" id="id_dni" required>
    <br>
    <input type="submit" value="Guardar">
</form>
<div>
    <a href="{% url 'listado_proveedores' %}">Volver a listado de Proveedores</a>
</div>